# Generated by Django 4.0.4 on 2022-05-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='job_comp_name',
            new_name='companyname',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='job_experience',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='job_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='job_salary',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='job_title',
            new_name='title',
        ),
    ]
